spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1111
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type: TRACE
server:
  servlet:
    context-path: /api
